name: 'Trivy Security Scan'

on:
  push:
    branches: ['main', 'master']
  pull_request:
    branches: ['main', 'master']

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        id: trivy-step
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'json'
          exit-code: '1'
          output: 'trivy-results.json'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true

      - name: Report Trivy Results to PR
        uses: periphery-security/action-privy@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          trivy-results: 'trivy-results.json'

      - name: Fail job if vulnerabilities were found
        if: steps.trivy-step.outcome == 'failure'
        run: |
          echo "Se detectaron vulnerabilidades críticas o altas en el proyecto."
          exit 1
