name: 'Trivy Security Scan'

on:
  push:
    branches: ['main', 'develop', 'dev', 'release/*']
  pull_request:
    branches: ['main', 'develop', 'dev', 'release/*']

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Run Trivy vulnerability scanner
        id: trivy-step
        uses: aquasecurity/trivy-action@d2a0b60797ff03db6132bd4e2b293f9b37081297
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          exit-code: '1'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true

      - name: Upload SARIF to GitHub code scanning
        if: ${{ !cancelled() }}
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
          sarif_file: trivy-results.sarif

      - name: Upload Trivy report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: trivy-results
          path: trivy-results.sarif
          if-no-files-found: ignore

      - name: Fail job if vulnerabilities were found
        if: steps.trivy-step.outcome == 'failure'
        run: |
          echo "Se detectaron vulnerabilidades críticas o altas en el proyecto."
          exit 1
